config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  get 'name' => 'home#name'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def tinh()
        puts "hello Phuc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(s)
        if s.empty?
            return "Health"
        else
            "Health" + " | " + s
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<% provide(:tit, "Home") %>

<%= render 'layouts/header' %>

app/views/home/name.html.erb
<% provide(:tit,"Chỉ số cơ thể") %>
<%= render 'layouts/header' %>
<div><b>Thông tin</b></div>
<div>
    <p>-<b>Chỉ số khối cơ thể</b> - thường được biết đến với chữ viết tắt <b>BMI</b> theo tên tiếng Anh Body Mass Index - được dùng để đánh giá mức độ gầy hay béo của một người. Chỉ số này do nhà bác học người Bỉ Adolphe Quetelet đưa ra năm 1832</p>
    <p>-Chỉ số này có thể giúp xác định một người bị <b>bệnh béo phì</b> hay bị <b>bệnh suy dinh dưỡng</b> thông qua số liệu về hình dáng, chiều cao và cân nặng cơ thể.</p>
</div>
<div>
    <form>
    <label>Giới tính :        </label>
    <input type="radio", name="sex", value="Nam" />
    <label>Nam</label>
    <input type="radio", name="sex", value="Nữ" />
    <label>Nữ</label>
    <input type="radio", name="sex", value="khong biet" />
    <label>Không xác định</label>
    </form>
    <form>
        <label style="width:100px">Tuổi</label>
        <input type="text", name="age", style="width:200px" />
    </form>
    <form>
        <label style="width:100px">Chiều cao</label>
        <input type="text", name="height", style:"width:200px" />
        <label>cm</label>
    </form>
    <form>
        <label style="width:100px">Cân nặng</label>
        <input type="text", name="weight", style="width:200px" />
        <label>kg</label>
    </form>
    <form>
        <button type="button" class="btn btn-default">Tính toán</button>
    </form>
    <form>
        <button type="button" class="btn btn-default">Thiết lập lại</button>
    </form>
</div>

app/views/layouts/_header.html.erb
<ul class="nav nav-pills">
  <li class="active"><%= link_to "Trang chủ", "#" %></li>
  <li class="active"><%= link_to "Chỉ số cơ thể", name_path %><li>
  <li class="active"><%= link_to "Calo cho cân", "#" %></li>
  <li class="active"><%= link_to "Mục tiêu nhịp tim", "#" %></li>
  <li class="active"><%= link_to "Thể tích máu", "#" %></li>
  <li class="active"><%= link_to "Cồn trong máu", "#" %></li>
  <li class="active"><%= link_to "Lượng nước", "#" %></li>
  <li class="active"><%= link_to "Trọng lượng lý tưởng", "#" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:tit)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>